HANDLES = %w[
  itsocietymmu
  acsmmu
  buddhistsociety.mmu
  byic.mmu
  official_clsc_mmu
  commsocietymmu
  cmcmmu
  cac.mmu
  mmu.dice
  ebeevocals
  engsoc_mmucyb
  techgirls_mmu
  gdg.mmu
  iucyber
  iss_mmucyber
  jcsmmu
  kcc_cyber
  mmucscyber
  fcammu
  radiommu
  gdcmmu
  ieeemmusb
  srcmmu_cyber
  mmusuperheroes
  rentakmmu
  srmcyber
  shsommu
  sccmmu_cyber
  tamucyb
  mmu.akido_club
  badmintonclubmmucyber
  mmucyberjayachessclub
  volbees_mmu
  mmucyberjayarchery
  mmusports
  mmuswimmingclub
  mmufccyber
  mmuwatersports
  netbeesmmu
  oarsmmucyber
  mmuhornbillsreds
].freeze

HANDLES.each { |handle| Account.find_or_create_by!(handle: handle) }
